theme: jekyll-theme-minimal
author: Elliott Hirko
description: Here is a site I am deticating to my projects for the purpose of display as well as providing useful documentation to others performing similar work.
