theme: minima
title: Fusor Projects
author: Elliott Hirko
description: Here is a site I am deticating to my projects for the purpose of display as well as providing useful documentation to others performing similar work.
defaults:
  - scope:
      path: "_posts/Fusor"
    values:
      type: "Fusor"
  - scope:
      path: "_posts/Chemistry"
    values:
      type: "Chemistry"
